### PR TITLE
Fix error in load_local_synthetic_data.patch file

### PR DESCRIPTION
**Pull request by mtrang1263**
### Change Details

Fixing missing curly brace in load_local_synthetic_data.patch file. This caused compilation errors in RifLoaderIT.java.

Resolves regression introduced by https://github.com/CMSgov/beneficiary-fhir-data/pull/346

### Acceptance Validation

1. After running `make loadable`, verified that we can run `make load` successfully.

### Security Implications
- [ ] new software dependencies
- [ ] altered security controls
- [ ] new data stored or transmitted
- [ ] security checklist is completed for this change
- [ ] requires more information or team discussion to evaluate security implications

### CODE REVIEW

File: contributing/patches/load_local_synthetic_data.patch [hunk 1]
```diff
@@ -252,13 +252,13 @@ index a1401b55..a44fca81 100644
...
-index a163268d..b067192b 100644
+index a163268d..5378d8ce 100644
 --- a/apps/bfd-pipeline/bfd-pipeline-rif-load/src/test/java/gov/cms/bfd/pipeline/rif/load/RifLoaderIT.java
 +++ b/apps/bfd-pipeline/bfd-pipeline-rif-load/src/test/java/gov/cms/bfd/pipeline/rif/load/RifLoaderIT.java
-@@ -315,6 +315,19 @@ public final class RifLoaderIT {
-     } finally {
+@@ -316,6 +316,20 @@ public final class RifLoaderIT {
        if (entityManager != null) entityManager.close();
      }
+   }
```
Comment (mtrang1263) [inline contributing/patches/load_local_synthetic_data.patch:261]: Here's the missing curly brace that was causing the build error

Comment (jzulim) [reply contributing/patches/load_local_synthetic_data.patch:261]: Awesome. Thank you.

**Review by jzulim — APPROVED** [review]
Looks good to me. Thanks.

**Comment by jzulim** [comment]
@keithdadkins - This fix resolves a syntax issue introduced into our local docker setup. We'll want this merged before we can get you going locally. I've confirmed this 1 character fix. Mind looking at the patch and confirming this fix? Happy to review with you during our 1:1 as well.

**Review by keithdadkins — APPROVED** [review]
LGTM
